# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4131f177750a448aa35735b10206baf8690cb17e78d779e7d4dfd008ac6f366704fb5426c5d5baf70debe0196b459ac8a349b39b444c95db0fdb0e2652112492

test:
  secret_key_base: 75c5b154e0177d94178dc8678b3cf4df2aa229ffe82730351dd09512edac1b8ffca4fd805152ca1184e518ae76025f453fcbd10c8fd81afde214bc75e812e76e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
